# Generated by Django 4.2.5 on 2023-10-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_recipes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['title'], 'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(null=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
