# Generated by Django 4.2.5 on 2023-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_ingredients_options_products_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.BooleanField(default='True', verbose_name='Наличие'),
        ),
    ]
