# Generated by Django 4.2.5 on 2023-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_alter_products_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
